id: IA41844C0
legacy_id: P006859
ocr_import_info:
  bdrc_scan_id: W1KG9608
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:27:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:27:48.419421+00:00'
last_modified: 2022-08-27 16:28:01.012971
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9608
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9608
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷ་ས་གཙུག་ལག་ཁང་གི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་ཆ།
statistics:
  ocr_word_mean_confidence_index: 0.5361048024431897
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1KG9613:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9613
      total_pages: 89
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9613.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5361048024431897
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
